baseurl: /
permalink: /blog/:year/:month/:day/:title
url: "http://cocoabeans.io"
name: "Cocoa Beans Software"
description: "Cocoa Beans Software Ltd's official Website"
timezone: Europe/London
highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
encoding: utf-8
safe: true
lsi: false
