baseurl: /
permalink: /blog/:year/:month/:day/:title
url: http://cocoabeans.me
name: Cocoa Beans
description: "Cocoa Beans Ltd Official Website"
timezone: Europe/London
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
encoding: utf-8
safe: true
lsi: false